apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: tooling
  source:
    path: manifests/argo-workflows
    repoURL: https://github.com/volodymyr-stoiko/argodemo-projects.git
    targetRevision: master
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
