apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tooling
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: tooling
  source:
    path: manifests/argocd
    repoURL: https://github.com/volodymyr-stoiko/argodemo-projects.git
    targetRevision: master
  syncPolicy:
    automated:
      allowEmpty: true
      prune: false
      selfHeal: true
