---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Tooling workloads
  destinations:
  - namespace: default
    server: https://kubernetes.default.svc
  - namespace: argo
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/volodymyr-stoiko/argodemo-workloads.git
